apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: main
    path: charts/alertmanager
  destination:
    server: https://kubernetes.default.svc
    namespace: alertmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

